# Generated by Django 5.1.4 on 2026-06-23 00:00

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repos', '0001_enable_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(unique=True)),
                ('branch', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cloning', 'Cloning'), ('indexing', 'Indexing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('file_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'repositories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=1024)),
                ('language', models.CharField(blank=True, default='', max_length=64)),
                ('start_line', models.PositiveIntegerField(default=1)),
                ('end_line', models.PositiveIntegerField(default=1)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='repos.repository')),
            ],
            options={
                'indexes': [models.Index(fields=['repository', 'file_path'], name='repos_codec_reposit_85fd36_idx'), pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='codechunk_embedding_hnsw', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
