# Generated by Django 5.1.4 on 2026-06-23 14:51

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codechunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=384),
        ),
    ]
