# Generated by Django 5.1.4 on 2026-06-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0003_alter_codechunk_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cloning', 'Cloning'), ('indexing', 'Indexing'), ('cancelling', 'Cancelling'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
